---
title: "Code to Process Raw Output from the HPC Cluster"
author: "Sydney Louit"
#graphics: yes
output: 
  pdf_document: default
  keep_tex: false
---

Code block:

```{r echo = FALSE, results = 'asis'}
source('sbm_functions.R')
K <- 2
nbeta <- K^2 + 1
base_path <- paste0('../../Archives/fixed_k_raw_data/', K, '_groups/all_data_')

## Initialize summary
sim_mean <- matrix(0, nrow = 100, ncol = nbeta)
sim_se <- matrix(0, nrow = 100, ncol = nbeta)
sim_low <- matrix(0, nrow = 100, ncol = nbeta)
sim_median <- matrix(0, nrow = 100, ncol = nbeta)
sim_high <- matrix(0, nrow = 100, ncol = nbeta)

## Iterate over raw data to find values
for (i in 1:100){
  replicate <- read.csv(paste0(base_path, i, '_', K, '_groups.csv'))
  for (j in 1:nbeta){
    sim_mean[i, j] <- mean(replicate[, j])
    sim_se[i, j] <- sd(replicate[, j])
    sim_low[i, j] <- quantile(replicate[, j], 0.025)
    sim_median[i, j] <- quantile(replicate[, j], 0.5)
    sim_high[i, j] <- quantile(replicate[, j], 0.975)
  }
}

true_values <- c(1.5 * diag(K) - 3, 1)
sim_bias <- t(t(sim_mean) - true_values) 
for (i in 1:ncol(sim_low)){
  coverage <- length(which(sim_low[, i] <= true_values[i]
                           & true_values[i] <= sim_high[, i]))
  print(coverage / 100)
}


beta_column <- 1
mcmc_summary <- data.frame(
    replicate = 1:100,
    mean = sim_mean[, beta_column],
    se = sim_se[, beta_column],
    bias = sim_bias[, beta_column],
    ci_low = sim_low[, beta_column],
    ci_med = sim_median[, beta_column],
    ci_high = sim_high[, beta_column]
)

#as.data.frame(sim_mean)
mcmc_summary
```

```{r echo = FALSE, results = 'asis'}
## Plot trace plots for a replicate
par(mfrow = c(3, 2))
samp <- rcat(1, rep(1, 100)); print(samp)
#samp <- 1
replicate <- read.csv(paste0(base_path, samp, '_', K, '_groups.csv'))
plot.ts(replicate[, 1]); abline(-1.5, 0, col= 'red')
plot.ts(replicate[, 2]); abline(-3, 0, col = 'red')
plot.ts(replicate[, 3]); abline(-3, 0, col = 'red')
plot.ts(replicate[, 4]); abline(-1.5, 0, col = 'red')
plot.ts(replicate[, 5]); abline(1, 0, col = 'red')

```
