---
title: "calfsbm-vignette"
author: "Sydney Louit"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{rCASC Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

This is a vignette demonstrating basic usage of our CALF-SBM model 

## Load the rest of the package
```{r}
source('../R/sbm_functions.R')
```

## Generate a network according to the model's specifications

```{r}
set.seed(123)
## Set constants
n_nodes <- 400 # Network size
K <- 4 # True number of clusters
m <- 2 # Number of node-specific covariates
block_size <- rep(1/4, 4) # Vector of block probabilities
beta0 <- 1 # Network sparsity
beta <- diag(4) - 3 # Matrix of true beta parameters
sigma <- 0.3 # Node heterogeneity parameter
signal_to_noise <- 2
directed <- FALSE # Undirected network

links <- generate_calfsbm_network(n_nodes, K, m, block_size, 
                                  beta0, beta, sigma, signal_to_noise, 
                                  directed)

```

## Evaluate characteristics of the network

```{r }
## Density
mean(links$A)
## Block sizes
table(links$z)
## Plot nodes by their covariates
plot(links$X, col = links$z, pch = 20, main = 'Node Covariates and Configuration')
```

## With help from the NIMBLE package, run MCMC simulations

```{r}
## Water down simulation numbers for ease of use
nsim <- 1000
burnin <- 500
thin <- 10
nchain <- 3
K <- 4
mcmcSamples <- calf_sbm_nimble(links, nsim, burnin, thin, nchain, K, 
                               return_gelman = TRUE)


```
